baseURL = "https://matmoore.github.io/accelerator/"
languageCode = "en-gb"
title = "Accelerator project journal"
theme = "Journal"

relativeURLs = true
CanonifyURLs = true

# Deployment via docs folder for GitHub
publishDir = "../docs"

displayMath = [['$$','$$'], ['\\[','\\]']]

[params]
  description = "A 3 month project to mine click logs for evaluating and improving searches for public information"
  tagline = "A 3 month project to mine click logs for evaluating and improving site search"


[taxonomies]
  tag = "tags"